In [1]:
import numpy as np


In [3]:
# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정
R = np.array([[4, np.NaN, np.NaN, 2, np.NaN],
             [np.NaN, 5, np.NaN, 3, 1],
             [np.NaN, np.NaN, 3, 4, 4],
             [5, 2, 1, 2, np.NaN]])

num_users, num_items = R.shape
K = 3

# P와 Q 행렬의 크기를 지정하고 정규 분포를 가진 임의의 값으로 입력합니다.
np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))




In [6]:
from sklearn.metrics import mean_squared_error


def get_rmse(R, P, Q, non_zeros):
    error=0
    #  두 개의 분해된 행렬 P와 Q.T의 내적으로 예측 R 행렬 생성
    full_pred_matrix = np.dot(P, Q.T)

    #  실제 R 행렬에서 널이 아닌 값의 위치 인덱스 추출해 실제 R 행렬과 예측 행렬의 RMSE 추출
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)

    return rmse





In [8]:
# R > 0인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장.
non_zeros = [(i, j, R[i,j]) for i in range(num_users) for j in range(num_items) if R[i, j] > 0]

steps = 1000
learning_rate = 0.01
r_lambda = 0.01

# SGD 기법으로 P와 Q 매트릭스를 계속 업데이트.
for step in range(steps):
    for i, j, r in non_zeros:
        # 실제 값과 예측 값의 차이인 오류 값 구함
        eij=  r - np.dot(P[i, :], Q[j, :].T)
        # Regularization을 반영한 SGD 업데이트 공식 적용
        P[i, :] = P[i, :] + learning_rate*(eij * Q[j, :] - r_lambda*P[i, :])
        Q[j, :] = Q[j, :] + learning_rate*(eij * P[i, :] - r_lambda*Q[j, :])

        rmse = get_rmse(R, P, Q, non_zeros)
        if (step % 50) ==0:
            print('### iteration step:', step, "rmse :", rmse)





### iteration step: 0 rmse : 3.261355059488935
### iteration step: 0 rmse : 3.26040057174686
### iteration step: 0 rmse : 3.253984404542389
### iteration step: 0 rmse : 3.2521583839863624
### iteration step: 0 rmse : 3.252335303789125
### iteration step: 0 rmse : 3.251072196430487
### iteration step: 0 rmse : 3.2492449982564864
### iteration step: 0 rmse : 3.247416477570409
### iteration step: 0 rmse : 3.241926055455223
### iteration step: 0 rmse : 3.2400454107613084
### iteration step: 0 rmse : 3.240166740749792
### iteration step: 0 rmse : 3.2388050277987723
### iteration step: 50 rmse : 0.5003190892212749
### iteration step: 50 rmse : 0.5001616291326989
### iteration step: 50 rmse : 0.4989960120257809
### iteration step: 50 rmse : 0.498848345014583
### iteration step: 50 rmse : 0.4989518925663175
### iteration step: 50 rmse : 0.4983323683009099
### iteration step: 50 rmse : 0.4984148489378701
### iteration step: 50 rmse : 0.49792599580240876
### iteration step: 50 rmse : 0.490060556

In [9]:
pred_matrix = np.dot(P, Q.T)
print('예측 행렬:\n', np.round(pred_matrix, 3))

예측 행렬:
 [[3.991 0.897 1.306 2.002 1.663]
 [6.696 4.978 0.979 2.981 1.003]
 [6.677 0.391 2.987 3.977 3.986]
 [4.968 2.005 1.006 2.017 1.14 ]]
